name: Scrape

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'

      - name: Write config
        run: echo "$CONFIG_DEFAULT" > config/default.ts
        env:
          CONFIG_DEFAULT: ${{ secrets.CONFIG_DEFAULT }}

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm start
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
